# nuScenes dataset.

_target_: torchbox3d.prototype.loader.DataModule # Mapping to Python class for `hydra`.
_recursive_: false

batch_size: ${model.batch_size}
num_workers: ${model.num_workers}
root_dir: ${oc.env:HOME}/data/datasets/nuscenes-bf16/sensor

dataset_name: nuscenes-bf16

_train_dataset:
  _target_: torchbox3d.prototype.loader.DataLoader
  root_dir: ${..root_dir}
  dataset_name: ${..dataset_name}
  split_name: train
  range_view_config:
    height: 32
    width: 1800
  targets_config: ${model._head.targets_config}

_val_dataset:
  _target_: torchbox3d.prototype.loader.DataLoader
  root_dir: ${..root_dir}
  dataset_name: ${..dataset_name}
  split_name: val
  range_view_config: ${.._train_dataset.range_view_config}

_test_dataset:
  _target_: torchbox3d.prototype.loader.DataLoader
  root_dir: ${..root_dir}
  dataset_name: ${..dataset_name}
  split_name: test
  range_view_config: ${.._train_dataset.range_view_config}
