name: tb3
channels:
  - conda-forge
dependencies:
  - gxx==10.*
  - hydra-core
  - kornia
  - matplotlib-base
  - mmcv
  - numba
  - numpy
  - omegaconf
  - openblas
  - pandas
  - pip
  - polars
  - pyarrow
  - pytorch
  - pytorch-lightning
  - pyyaml
  - rich
  - ruff
  - rust
  - scipy
  - tensorflow==2.11.0
  - torchsparse
  - torchvision
  - universal_pathlib
  - wandb
  - pip:
      - hydra-submitit-launcher
      - git+https://github.com/argoverse/av2-api.git
